name: alquilados_app
description: "Aplicación móvil de gestión de alquileres e inmuebles"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.3

dependencies:
  dio: ^5.8.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  flutter_secure_storage: ^11.1.1
  freezed_annotation: any
  go_router: ^18.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  path_provider: ^2.1.5
  riverpod_annotation: any
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  riverpod_generator: any

flutter:
  uses-material-design: true
